linters:
  enable-all: true
  disable:
    - paralleltest
    - revive
    - stylecheck
    - testpackage
    - unused
    - varnamelen
    - whitespace
    - wsl
    # deprecated linters
    - interfacer
    - maligned
    - scopelint
  fast: true
