name: Deploy to GCP

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}
      nextjs: ${{ steps.filter.outputs.nextjs }}
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            go:
              - 'go/**'
            nextjs:
              - 'nextjs/**'
            terraform:
              - 'terraform/**'

  go-cmd-pubsub:
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go/cmd/pubsub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Build and push image
        run: gcloud builds submit --tag eu.gcr.io/${{ secrets.project_id }}/go-cmd-pubsub --project ${{ secrets.project_id }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy go-cmd-pubsub \
            --image eu.gcr.io/${{ secrets.project_id }}/go-cmd-pubsub \
            --project ${{ secrets.project_id }} \
            --platform managed \
            --region europe-west1

  go-cmd-web:
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go/cmd/web
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v0.6.0
      - run: |
          gcloud builds submit \
          --tag eu.gcr.io/${{ secrets.project_id }}/go-cmd-web \
          --project ${{ secrets.project_id }}

  nextjs:
    needs: changes
    if: ${{ needs.changes.outputs.nextjs == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nextjs
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v0.6.0
      - run: |
          gcloud builds submit \
          --tag eu.gcr.io/${{ secrets.project_id }}/nextjs \
          --project ${{ secrets.project_id }}
      - run: |
          gcloud run deploy nextjs \
          --image eu.gcr.io/${{ secrets.project_id }}/nextjs \
          --project ${{ secrets.project_id }} \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated

  terraform:
    needs: [go-cmd-web]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
      - run: terraform apply -auto-approve -input=false
