name: Deploy on push to main branch

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      domain: ${{ steps.filter.outputs.domain }}
      springapi: ${{ steps.filter.outputs.springapi }}
      nextjs-website: ${{ steps.filter.outputs.nextjs-website }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            springapi:
              - 'springapi/**'
            nextjs-website:
              - 'nextjs-website/**'

  build-and-deploy-api:
    needs: [changes, build-and-deploy-domain-module]
    if: ${{ always() && needs.changes.outputs.springapi == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: springapi

    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: "Build with Maven"
        run: mvn --batch-mode --update-snapshots verify

      - name: "Copy JAR to staging folder"
        run: mkdir staging && cp target/*.jar staging

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          # TODO: Change to workload_identity_provider
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0

      - name: Deploy JAR to App Engine
        run: gcloud app deploy staging/springapi-0.0.1-SNAPSHOT.jar

  build-and-deploy-website:
    needs: changes
    if: ${{ needs.changes.outputs.nextjs-website == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nextjs-website

    steps:
      - uses: actions/checkout@v2
      - name: Build nextjs-website Docker image
        run: docker build -t nextjs-website .

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          # TODO: Change to workload_identity_provider
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0

      - name: Upload nextjs-website image to Container Registry
        run: gcloud builds submit --tag gcr.io/${{ secrets.project_id }}/nextjs-website --project ${{ secrets.project_id }}

      - name: Deploy nextjs-website to Cloud Run
        run: |
          gcloud run deploy nextjs-website \
          --image gcr.io/${{ secrets.project_id }}/nextjs-website \
          --project ${{ secrets.project_id }} \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated
