name: Deploy on push to main branch

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: movielist

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: movielist-appengine
      #     path: staging

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          project_id: ${{ secrets.project_id }}

      - name: Deploy to App Engine
        run: gcloud app deploy staging/movielist-0.0.1-SNAPSHOT.jar
