name: Deploy to GCP

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}
      nextjs: ${{ steps.filter.outputs.nextjs }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            go:
              - 'go/**'
            nextjs:
              - 'nextjs/**'

  go-run-pubsub-service:
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go/run-pubsub-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v0
        with:
          # TODO: Change to workload_identity_provider
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Push image to Container Registry
        run: gcloud builds submit --tag gcr.io/${{ secrets.project_id }}/go-run-pubsub-service --project ${{ secrets.project_id }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy go-run-pubsub-service \
            --image gcr.io/${{ secrets.project_id }}/go-run-pubsub-service \
            --project ${{ secrets.project_id }} \
            --platform managed \
            --region europe-west1

  go-cmd-web:
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go/run-web-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v0
        with:
          # TODO: Change to workload_identity_provider
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Push image to Container Registry
        run: gcloud builds submit --tag gcr.io/${{ secrets.project_id }}/go-run-web-service --project ${{ secrets.project_id }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy go-run-web-service \
            --image gcr.io/${{ secrets.project_id }}/go-run-web-service \
            --project ${{ secrets.project_id }} \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated

  nextjs:
    needs: changes
    if: ${{ needs.changes.outputs.nextjs == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nextjs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v0
        with:
          # TODO: Change to workload_identity_provider
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Push image to Container Registry
        run: |
          gcloud builds submit \
          --tag gcr.io/${{ secrets.project_id }}/nextjs \
          --project ${{ secrets.project_id }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nextjs \
          --image gcr.io/${{ secrets.project_id }}/nextjs \
          --project ${{ secrets.project_id }} \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated
