name: pull request merge

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      go-run-pubsub-service: ${{ steps.filter.outputs.go-run-pubsub-service }}
      go-run-web-service: ${{ steps.filter.outputs.go-run-web-service }}
      ts-nextjs-website: ${{ steps.filter.outputs.ts-nextjs-website }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            go-run-pubsub-service:
              - 'go-run-pubsub-service/**'
            go-run-web-service:
              - 'go/run-web-service/**'
            ts-nextjs-website:
              - 'ts-nextjs-website/**'

  go-run-pubsub-service:
    needs: changes
    if: ${{ needs.changes.outputs.go-run-pubsub-service == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go-run-pubsub-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t go-run-pubsub-service .

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v0
        with:
          # TODO: Change to workload_identity_provider
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Push image to Container Registry
        run: gcloud builds submit --tag gcr.io/${{ secrets.project_id }}/go-run-pubsub-service --project ${{ secrets.project_id }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy go-run-pubsub-service \
            --image gcr.io/${{ secrets.project_id }}/go-run-pubsub-service \
            --project ${{ secrets.project_id }} \
            --platform managed \
            --region europe-west1

  go-run-web-service:
    needs: changes
    if: ${{ needs.changes.outputs.go-run-web-service == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go-run-web-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t go-run-web-service .

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v0
        with:
          # TODO: Change to workload_identity_provider
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Push image to Container Registry
        run: gcloud builds submit --tag gcr.io/${{ secrets.project_id }}/go-run-web-service --project ${{ secrets.project_id }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy go-run-web-service \
            --image gcr.io/${{ secrets.project_id }}/go-run-web-service \
            --project ${{ secrets.project_id }} \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated

  ts-nextjs-website:
    needs: changes
    if: ${{ needs.changes.outputs.ts-nextjs-website == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ts-nextjs-website
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t ts-nextjs-website .

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v0
        with:
          # TODO: Change to workload_identity_provider
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Push image to Container Registry
        run: gcloud builds submit --tag gcr.io/${{ secrets.project_id }}/ts-nextjs-website --project ${{ secrets.project_id }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ts-nextjs-website \
          --image gcr.io/${{ secrets.project_id }}/ts-nextjs-website \
          --project ${{ secrets.project_id }} \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated
