name: pull request checks

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      go-pubsub-service: ${{ steps.filter.outputs.go-pubsub-service }}
      go-webservice: ${{ steps.filter.outputs.go-webservice }}
      nextjs-website: ${{ steps.filter.outputs.nextjs-website }}
      springapi: ${{ steps.filter.outputs.springapi }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            go-pubsub-service:
              - 'go-pubsub-service/**'
            go-webservice:
              - 'go-webservice/**'
            nextjs-website:
              - 'nextjs-website/**'
            springapi:
              - 'springapi/**'

  check-go-pubsub-service:
    needs: changes
    if: ${{ needs.changes.outputs.go-pubsub-service == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go-pubsub-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Build
        run: go build -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Run tests
        run: go test ./...

  check-go-webservice:
    needs: changes
    if: ${{ needs.changes.outputs.go-webservice == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go-webservice
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Build
        run: go build -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Run tests
        run: go test ./...

  check-nextjs-website:
    needs: changes
    if: ${{ needs.changes.outputs.nextjs-website == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nextjs-website
    steps:
      - uses: actions/checkout@v3
      - name: Build nextjs-website Docker image
        run: docker build -t nextjs-website .

  check-springapi:
    needs: [changes]
    if: ${{ always() && needs.changes.outputs.springapi == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: springapi
    steps:
      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          # TODO: Change to workload_identity_provider
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: "Set up JDK 11"
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"

      - name: "Build with Maven"
        run: mvn --batch-mode --update-snapshots verify
