name: Status check on pull request to main branch

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-domain-model:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: movielist-domain-model
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@master
        with:
          name: movielist-domain-model
          path: staging/

  build-api:
    runs-on: ubuntu-latest
    needs: build-domain-model
    defaults:
      run:
        working-directory: movielist
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/download-artifact@master
        with:
          name: movielist-domain-model
          path: ~/.m2/repository
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - run: mvn --batch-mode --update-snapshots verify

  build-website:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: movielist-website
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t movielist-website .
