name: Status check on pull request to main branch

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: springapi
    steps:
      - uses: actions/checkout@v2

      - name: "Setup gcloud CLI"
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          project_id: ${{ secrets.project_id }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: "Build with Maven"
        run: mvn --batch-mode --update-snapshots verify

  build-nextjs-website:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nextjs-website
    steps:
      - uses: actions/checkout@v2
      - name: Build nextjs-website Docker image
        run: docker build -t nextjs-website .
