name: Status check on pull request to main branch

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      domain: ${{ steps.filter.outputs.domain }}
      go-webservice: ${{ steps.filter.outputs.go-webservice }}
      nextjs-website: ${{ steps.filter.outputs.nextjs-website }}
      springapi: ${{ steps.filter.outputs.springapi }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            domain:
              - 'domain/**'
            nextjs-website:
              - 'nextjs-website/**'
            springapi:
              - 'springapi/**'

  domain:
    needs: changes
    if: ${{ needs.changes.outputs.domain == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: domain
    steps:
      - uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          # TODO: Change to workload_identity_provider
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: "Build with Maven"
        run: mvn --batch-mode --update-snapshots install

  build-go-webservice:
    needs: changes
    if: ${{ needs.changes.outputs.go-webservice == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go-webservice
    steps:
      - uses: actions/checkout@v2
      - name: Build go-webservice Docker image
        run: docker build -t go-webservice .

  build-nextjs-website:
    needs: changes
    if: ${{ needs.changes.outputs.nextjs-website == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nextjs-website
    steps:
      - uses: actions/checkout@v2
      - name: Build nextjs-website Docker image
        run: docker build -t nextjs-website .

  build-api:
    needs: [changes, domain]
    if: ${{ always() && needs.changes.outputs.springapi == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: springapi
    steps:
      - uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          # TODO: Change to workload_identity_provider
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: "Build with Maven"
        run: mvn --batch-mode --update-snapshots verify
