steps:
  # Build docker image
  - id: "docker-build"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/go-webservice:$SHORT_SHA", "."]
    dir: "go-webservice"

  # Push docker image to registry
  - id: "push-to-registry"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/go-webservice:$SHORT_SHA"]
    dir: "go-webservice"

  # Deploy docker image to Cloud Run
  - id: "deploy-to-cloud-run"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - -c
      - |
        gcloud run deploy go-webservice \
        --image=eu.gcr.io/$PROJECT_ID/go-webservice:$SHORT_SHA \
        --region europe-west1 \
        --platform managed
    dir: "go-webservice"

images:
  - eu.gcr.io/$PROJECT_ID/go-webservice:$SHORT_SHA
